/**
 * PREMIUM DASHBOARD 🏠
 * 
 * Glassmorphism dashboard with stats and recent crystals
 * Mobile-first responsive design
 */

'use client';

import { useEffect, useState } from 'react';
import { Button, Card, CardHeader, CardTitle, CardContent, Badge } from '@/design';
import { motion } from 'framer-motion';
import {
    Plus,
    Zap,
    TrendingUp,
    Clock,
    Users,
    Sparkles,
    ArrowRight,
    Menu,
    ShieldAlert,
    Wallet,
    Target,
    Activity,
    Brain,
    Layers
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import { MobileNav } from '@/components/MobileNav';
import { Sidebar } from '@/components/Sidebar';

interface DashboardStats {
    total_crystals: number;
    today_crystals: number;
    cache_hit_rate: number;
    estimated_savings_usd: number;
    truth_fidelity: number;
    threats_neutralized: number;
    neural_density: number;
    time_saved_hours: number;
}

export default function PremiumDashboard() {
    const router = useRouter();
    const [stats, setStats] = useState<DashboardStats>({
        total_crystals: 0,
        today_crystals: 0,
        cache_hit_rate: 92,
        estimated_savings_usd: 0,
        truth_fidelity: 0.992,
        threats_neutralized: 0,
        neural_density: 0.2,
        time_saved_hours: 0
    });

    const [recentCrystals, setRecentCrystals] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const token = localStorage.getItem('token');
        const headers = { 'Authorization': `Bearer ${token}` };

        // Load personalized stats
        fetch(`${process.env.NEXT_PUBLIC_API_URL}/v1/analytics/my-stats`, { headers })
            .then(res => res.json())
            .then(data => {
                if (data.success && data.stats) {
                    setStats(data.stats);
                }
            })
            .catch(console.error)
            .finally(() => setLoading(false));

        // Load recent crystals
        fetch(`${process.env.NEXT_PUBLIC_API_URL}/v1/crystals?limit=5&sort=recent`, { headers })
            .then(res => res.json())
            .then(data => {
                if (data.success && data.crystals) {
                    setRecentCrystals(data.crystals);
                }
            })
            .catch(console.error);
    }, []);

    const statCards = [
        {
            label: 'Value Unlocked',
            value: `$${stats.estimated_savings_usd.toFixed(2)}`,
            subValue: 'Sovereign capital preserved',
            icon: Wallet,
            color: 'green',
            gradient: 'from-emerald-400 to-emerald-600',
            description: 'Direct savings generated by substituting LLM calls with Semantic Cache hits.'
        },
        {
            label: 'Cognitive Freedom',
            value: `${stats.time_saved_hours.toFixed(1)}h`,
            subValue: 'Manual research avoided',
            icon: Clock,
            color: 'blue',
            gradient: 'from-blue-400 to-indigo-600',
            description: 'Total hours reclaimed from manual knowledge synthesis through Neural Ingestion.'
        },
        {
            label: 'Integrity Fidelity',
            value: `${(stats.truth_fidelity * 100).toFixed(1)}%`,
            subValue: 'Personal truth index',
            icon: Target,
            color: 'purple',
            gradient: 'from-fuchsia-500 to-purple-600',
            description: 'The mathematical accuracy of your knowledge base, verified by Jury Protocol.'
        },
        {
            label: 'Neural Growth',
            value: `+${stats.total_crystals}`,
            subValue: 'Crystals in Cortex',
            icon: Activity,
            color: 'indigo',
            gradient: 'from-indigo-400 to-cyan-600',
            description: 'The expansion rate of your localized neural lattice and semantic depth.'
        },
    ];

    return (
        <div className="min-h-screen bg-black text-white flex">
            <Sidebar />

            <div className="flex-1 md:ml-72 relative overflow-hidden h-screen overflow-y-auto">
                {/* Header - Premium Brutalist */}
                <div className="bg-black/50 backdrop-blur-3xl border-b border-white/5 sticky top-0 z-40">
                    <div className="max-w-7xl mx-auto px-8 sm:px-12 py-10 flex items-center justify-between">
                        <div className="flex-1 min-w-0">
                            <div className="inline-flex items-center px-3 py-1 bg-white/5 rounded-full border border-white/10 mb-6">
                                <ShieldAlert size={12} className="text-emerald-400 mr-2" />
                                <span className="text-[8px] font-black uppercase tracking-[0.2em] text-white/60 text-emerald-400">Personal Value Ledger Active</span>
                            </div>
                            <h1 className="font-bebas text-8xl sm:text-9xl tracking-[0.02em] leading-[0.8] italic uppercase">
                                SOVEREIGN_<span className="text-white/20">IMPACT.</span>
                            </h1>
                            <p className="text-[10px] font-black uppercase tracking-[0.4em] text-white/30 mt-6 ml-1">
                                Real-time benefits captured by your neural bridge instance
                            </p>
                        </div>
                    </div>
                </div>

                {/* Main Content */}
                <div className="max-w-7xl mx-auto px-8 sm:px-12 py-12">
                    {/* Stats Row - Ultra Premium Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
                        {statCards.map((stat, idx) => {
                            const Icon = stat.icon;
                            return (
                                <motion.div
                                    key={stat.label}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: idx * 0.1 }}
                                >
                                    <div className="relative group overflow-hidden p-10 rounded-[3rem] bg-white/[0.02] border border-white/5 backdrop-blur-2xl hover:bg-white/[0.04] transition-all border-b-4 border-b-transparent hover:border-b-white/20">
                                        <div className="flex flex-col gap-8">
                                            <div className="flex items-center justify-between">
                                                <div className={`p-4 rounded-2xl bg-gradient-to-br ${stat.gradient} shadow-2xl`}>
                                                    <Icon className="text-white" size={20} />
                                                </div>
                                                <div className="text-right">
                                                    <span className="block text-[8px] font-black text-white/10 uppercase tracking-[0.3em]">Module_v2.4</span>
                                                    <span className="block text-[8px] font-black text-emerald-400/40 uppercase tracking-[0.3em] mt-1">Beneficiary_Sovereign</span>
                                                </div>
                                            </div>

                                            <div>
                                                <p className="text-[10px] text-white/30 font-black uppercase tracking-[0.3em] mb-3">
                                                    {stat.label}
                                                </p>
                                                <p className="text-5xl font-black text-white tracking-tighter italic leading-none">
                                                    {stat.value}
                                                </p>
                                                <p className="text-[9px] font-black text-white/40 mt-4 uppercase tracking-[0.1em]">
                                                    {stat.subValue}
                                                </p>
                                            </div>

                                            <div className="pt-8 border-t border-white/5">
                                                <p className="text-[9px] font-medium text-white/20 leading-relaxed uppercase tracking-widest text-justify">
                                                    {stat.description}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </motion.div>
                            );
                        })}
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
                        {/* Recent Crystals - Left Column */}
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.4 }}
                            className="lg:col-span-2"
                        >
                            <div className="rounded-[4rem] bg-white/[0.01] border border-white/5 p-12 relative overflow-hidden">
                                <div className="absolute top-0 right-0 p-12 opacity-5 pointer-events-none">
                                    <Brain size={200} />
                                </div>
                                <div className="flex items-center justify-between mb-12 relative z-10">
                                    <div>
                                        <h3 className="font-bebas text-6xl italic tracking-wide">ARTIFACT_FEED.</h3>
                                        <p className="text-[10px] font-black uppercase tracking-[0.3em] text-white/20 mt-2">Latest localized knowledge fragments</p>
                                    </div>
                                    <button
                                        onClick={() => router.push('/library')}
                                        className="px-8 py-3 rounded-2xl border border-white/10 text-[9px] font-black uppercase tracking-[0.3em] hover:bg-white hover:text-black transition-all shadow-2xl"
                                    >
                                        NAVIGATE_LATTICE
                                    </button>
                                </div>

                                <div className="space-y-4 relative z-10">
                                    {recentCrystals.length > 0 ? recentCrystals.map((crystal, idx) => (
                                        <motion.div
                                            key={crystal.id}
                                            initial={{ opacity: 0, x: -20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: 0.5 + idx * 0.1 }}
                                            className="flex items-center justify-between p-7 rounded-[2.5rem] bg-white/[0.02] border border-transparent hover:border-white/5 hover:bg-white/[0.04] transition-all cursor-pointer group"
                                            onClick={() => router.push(`/library`)}
                                        >
                                            <div className="flex items-center gap-8">
                                                <div className="w-14 h-14 rounded-2xl bg-white/5 flex items-center justify-center border border-white/10 group-hover:bg-emerald-500/20 group-hover:border-emerald-500/30 transition-all">
                                                    <Sparkles className="text-white/40 group-hover:text-emerald-400 transition-colors" size={24} />
                                                </div>
                                                <div>
                                                    <h3 className="font-black text-sm uppercase tracking-[0.2em] text-white/70 group-hover:text-white transition-colors">
                                                        {crystal.title}
                                                    </h3>
                                                    <div className="flex items-center gap-4 mt-2">
                                                        <span className="text-[8px] font-black uppercase text-indigo-400/60 bg-indigo-500/5 px-3 py-1 rounded-full border border-indigo-500/10">{crystal.domain}</span>
                                                        <span className="text-[8px] font-black text-white/20 uppercase tracking-[0.3em] flex items-center gap-2">
                                                            <Clock size={10} /> {new Date(crystal.created_at).toLocaleDateString()}
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="w-12 h-12 rounded-full border border-white/5 flex items-center justify-center group-hover:bg-white group-hover:text-black transition-all transform group-hover:rotate-45">
                                                <ArrowRight size={18} />
                                            </div>
                                        </motion.div>
                                    )) : (
                                        <div className="text-center py-20 rounded-[3rem] border border-dashed border-white/5">
                                            <p className="text-[10px] font-black uppercase tracking-[0.4em] text-white/20">No artifacts discovered yet</p>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </motion.div>

                        {/* Quick Actions - Right Column */}
                        <div className="space-y-8">
                            {[
                                { title: 'SYNTHESIZE', icon: Plus, path: '/ingest', desc: 'NEW_CRYSTALLIZATION', color: 'from-emerald-500', shadow: 'shadow-emerald-500/20' },
                                { title: 'OMNI_CORTEX', icon: Brain, path: '/cortex', desc: 'NEURAL_NAVIGATION', color: 'from-indigo-500', shadow: 'shadow-indigo-500/20' },
                                { title: 'THE_LOOM', icon: Layers, path: '/loom', desc: 'COMPLEX_SYNTHESIS', color: 'from-fuchsia-500', shadow: 'shadow-fuchsia-500/20' }
                            ].map((action, i) => (
                                <motion.div
                                    key={i}
                                    initial={{ opacity: 0, x: 20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: 0.6 + i * 0.1 }}
                                    onClick={() => router.push(action.path)}
                                    className="glass-panel group p-10 rounded-[3rem] text-center cursor-pointer hover:bg-white/5 transition-all relative overflow-hidden"
                                >
                                    <div className={`w-20 h-20 rounded-[2rem] bg-gradient-to-br ${action.color} to-black flex items-center justify-center mx-auto mb-8 shadow-2xl ${action.shadow} group-hover:scale-110 group-hover:rotate-12 transition-all duration-500`}>
                                        <action.icon className="text-white" size={32} />
                                    </div>
                                    <h3 className="font-bebas text-5xl italic tracking-wider mb-2">{action.title}.</h3>
                                    <p className="text-[9px] font-black uppercase tracking-[0.4em] text-white/20">
                                        {action.desc}
                                    </p>
                                    <div className="absolute bottom-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-white/10 to-transparent scale-x-0 group-hover:scale-x-100 transition-transform duration-700" />
                                </motion.div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
