import { DecisionReceipt } from './services/decision_receipts';

/**
 * Visualizer for Neural Bridge Decision Receipts.
 * Helps developers verify and display the "Zero Mock" proof in their own consoles or UIs.
 */
export class ReceiptVisualizer {
    
    /**
     * Render a receipt as a Markdown-formatted report string.
     * Useful for server logs or CLI output.
     */
    static toMarkdown(receipt: DecisionReceipt): string {
        const score = (receipt.verification.sri * 100).toFixed(1);
        const icon = receipt.verification.sri >= 0.85 ? '🟢' : (receipt.verification.sri >= 0.5 ? '🟡' : '🔴');
        const hashShort = receipt.signature.payload_hash.slice(0, 12) + '...';
        
        return `
# 🧾 Neural Bridge Decision Receipt
> **ID:** \`${receipt.receipt_id}\` | **Time:** ${receipt.timestamp}

## 🔒 Verification Status
**Result:** ${icon} ${receipt.verification.sri >= 0.85 ? 'PASSED' : 'FLAGGED'}
**SRI Score:** ${score}% (Semantic Reliability Index)
**Confidence:** ε = ${receipt.verification.pac_epsilon.toFixed(4)}

## 🧪 Semantic Checks (Zero Mock)
${receipt.verification.invariants_used.map(id => {
    const passed = receipt.verification.invariants_passed.includes(id);
    return `- [${passed ? 'x' : ' '}] **${id}**: ${passed ? '✅ PASS' : '❌ FAIL'}`;
}).join('\n')}

## 🧬 Context Crystal
- **Crystal ID:** \`${receipt.crystal_refs[0]?.crystal_id ?? 'unknown'}\`
- **Canonical Hash:** \`${receipt.crystal_refs[0]?.hash ?? 'unknown'}\`

## ✍️ Cryptographic Proof
- **Signature:** \`${receipt.signature.signature.slice(0, 32)}...\`
- **Signer Key:** \`${receipt.signature.public_key.slice(0, 16)}...\`
- **Integrity:** Verified (SHA-256 + ECDSA)

---
*Generated by Neural Bridge SDK - The Standard for Verifiable AI*
`.trim();
    }

    /**
     * Render a receipt as an HTML string (for web dashboards).
     */
    static toHTML(receipt: DecisionReceipt): string {
        const score = (receipt.verification.sri * 100).toFixed(0);
        const passed = receipt.verification.sri >= 0.85;
        const color = passed ? '#00FF94' : (receipt.verification.sri >= 0.5 ? '#FFD600' : '#FF2E54');
        const statusText = passed ? 'SECURE' : (receipt.verification.sri >= 0.5 ? 'WARNING' : 'BLOCKED');
        
        // CSS Variables simulated inline for portability
        const bgDeep = '#050508';
        const bgGlass = 'rgba(20, 20, 25, 0.6)';
        const border = '1px solid rgba(255, 255, 255, 0.08)';
        const textPrimary = '#FFFFFF';
        const textSecondary = '#8F90A6';
        
        return `
        <div style="font-family: 'Inter', system-ui, sans-serif; background: ${bgDeep}; color: ${textPrimary}; padding: 24px; border-radius: 16px; max-width: 600px; border: ${border}; box-shadow: 0 8px 32px rgba(0,0,0,0.4);">
            <div style="display:flex; justify-content:space-between; align-items:center; border-bottom: ${border}; padding-bottom: 16px; margin-bottom: 20px;">
                <div style="display:flex; align-items:center; gap:10px;">
                    <div style="width:12px; height:12px; border-radius:50%; background:${color}; box-shadow: 0 0 10px ${color};"></div>
                    <h3 style="margin:0; font-size:14px; letter-spacing:1px; text-transform:uppercase;">Decision Receipt</h3>
                </div>
                <span style="font-family: 'JetBrains Mono', monospace; font-size:10px; color:${textSecondary};">${receipt.receipt_id}</span>
            </div>
            
            <div style="display:grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px;">
                <div style="background:${bgGlass}; padding:16px; border-radius:12px; border:${border};">
                    <div style="font-size:10px; color:${textSecondary}; text-transform:uppercase; margin-bottom:4px;">SRI Score</div>
                    <div style="font-family: 'JetBrains Mono', monospace; font-size:32px; font-weight:800; color:${color};">${score}<span style="font-size:16px">%</span></div>
                </div>
                <div style="background:${bgGlass}; padding:16px; border-radius:12px; border:${border};">
                    <div style="font-size:10px; color:${textSecondary}; text-transform:uppercase; margin-bottom:4px;">Verification Status</div>
                    <div style="font-size:16px; font-weight:600; color:${textPrimary}; margin-top:8px; letter-spacing:0.5px;">${statusText}</div>
                </div>
            </div>

            <div style="background:${bgGlass}; padding: 16px; border-radius: 12px; margin-bottom: 20px; border:${border};">
                <div style="font-size:10px; color:${textSecondary}; margin-bottom:12px; text-transform:uppercase; letter-spacing:1px;">Semantic Invariants (Zero Mock)</div>
                <div style="display:flex; flex-direction:column; gap:8px;">
                    ${receipt.verification.invariants_used.map(id => {
                        const isPassed = receipt.verification.invariants_passed.includes(id);
                        return `
                        <div style="display:flex; justify-content:space-between; align-items:center; font-size:12px; padding-bottom:8px; border-bottom:1px solid rgba(255,255,255,0.03);">
                            <span style="font-family: 'JetBrains Mono', monospace; color:${textSecondary};">${id}</span>
                            <span style="font-weight:700; color:${isPassed ? '#00FF94' : '#FF2E54'}; background:${isPassed ? 'rgba(0,255,148,0.1)' : 'rgba(255,46,84,0.1)'}; padding:2px 8px; border-radius:4px;">
                                ${isPassed ? 'PASS' : 'FAIL'}
                            </span>
                        </div>`;
                    }).join('')}
                </div>
            </div>

            <div style="display:flex; justify-content:center; align-items:center; gap:8px; font-size:10px; color:${textSecondary}; opacity:0.8;">
                <span>🔒 Signed by Neural Bridge Protocol</span>
                <span>•</span>
                <span style="font-family:monospace;">${receipt.signature.signature.slice(0, 16)}...</span>
            </div>
        </div>
        `;
    }
}
